---
layout: page
title: "데이터 과학: 재현가능한 저작"
subtitle: "디지털 객체 식별자(DOI, Digital Object Identifiers)"
date: "`r Sys.Date()`"
author: xwMOOC
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
    lib_dir: gapminder
editor_options: 
  chunk_output_type: console
---

``` {r, include=FALSE}
# source("tools/chunk-options.R")
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```


# 저작자 카펜트리 [^author-carpentry] {#author-carpentry}

[Author Carpentry : Persistent access for research outputs with Digital Object Identifiers]: [](https://github.com/authorcarpentry/dois-citation-data/)

저작자 카펜트리(Author Carpentry)는 소프트웨어/데이터 카펜트리와 유사하게 기본적으로 저작자로서 알아야 되는 기본적인 
컴퓨팅 스킬을 라이브 코딩을 통해서 교육하고 관련 정보를 교류하는 자발적인 활동이다.
Gail Clement, Tom Morrell 두 분이 저작자 카펜트리 활동을 주도하고 있으며 관련된 자세한 정보는 [Author Carpentry](https://github.com/AuthorCarpentry)에서 확인할 수 있다.


<style>
  div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 10px;}
</style>
<div class = "blue">

**사전준비 사항**

논문 및 다양한 저작활동을 위해서 먼저 DOI를 갖는 논문을 갖추고 있어야 하며, 
DOI와 연계된 오픈 저장소에 기꺼이 공유할 수 있는 (발표자료, 데이터셋, 사진, 보고서 등) 학문 매체(scholarly object)가 준비되어야 한다.

[영어 원본: 소프트웨어 카펜트리 쉘 ](http://swcarpentry.github.io/shell-novice/), 
[한글 번역본: 유닉스 쉘](https://statkclee.github.io/shell-novice-kr/) 수업을 통해서 배쉬 쉘(bash shell)과 친숙해야만 된다.
배쉬 쉘이 설치되어 있어야 하고, 만약 설치가 필요한 경우 [Bash 쉘 (Bash Shell)](https://statkclee.github.io/2018-10-27-hallym/)을 참조하여 설치를 마무리 한다.

또한, 오픈소스 JSON 파싱 도구 jQuery도 [jq json parser](https://stedolan.github.io/jq/) 설치되어 API 서비스를 통해 얻어온 JSON 데이터를 보기 좋게 출력할 수 있어야 되고,
보편 문서 변환기 pandoc도 [pandoc 사이트](https://pandoc.org/)를 통해 설치하면 된다.

컨닝 쪽지(cheat sheet): `jQuery(jq)` API 참고문서: [https://oscarotero.com/jquery/](https://oscarotero.com/jquery/)

</div>

# 참고문헌

+ curl documentation, https://curl.haxx.se/
+ CrossRef REST API, https://github.com/CrossRef/rest-api-doc
+ CrossRef Content Negotiation, https://citation.crosscite.org/docs.html
+ Beyond the DOI to richer metadata, CrossRef Blog posting of June 15, 2016 by
April Ondis,
http://blog.crossref.org/2016/06/beyond-the-doi-to-richer-metadata.html
+ DataCite API, https://api.datacite.org/
+ Digital Object Identifier (DOI) Handbook, https://www.doi.org/hb.html
+ Digital Object Identifier System and DOI Names (DOIs) Guide from Australian
National Data Service, http://www.ands.org.au/guides/doi
+ DOI Citation Formatter beta, https://citation.crosscite.org
+ jq online testing tool, https://jqplay.org/
+ Parsing JSON with jq, http://www.compciv.org/recipes/cli/jq-for-parsing-json/
+ Pandoc User Manual, http://pandoc.org/MANUAL.html


# 디지털 객체 식별자 {#author-doi}