---
name: Byungjin
surname: Park
position: "Software Architect, Security Expert"
address: "42-8, Bangbae-ro 15-gil, Seocho-gu, Seoul, 00681, Rep. of KOREA"
phone: (+82) 10-9030-1843
www: www.posquit0.com
email: "posquit0.bj@gmail.com"
twitter: posquit0
github: posquit0
linkedin: posquit0
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
resume_df <- readRDS("../data/resume_df.rds")
```

# Summary

```{r resume-summary}
resume_df %>% 
  select(요약) %>% 
  unnest() %>% 
  brief_entries(요약)
```

# Work Experience

```{r vitae-work}
resume_df %>% 
  select(직장) %>% 
  unnest() %>% 
  detailed_entries(with=직장명, where=근무지, what=역할, when=근무연도)
```

<!-- # Honors & Awards -->

<!-- ```{r vitae-honors} -->
<!-- resume_df %>%  -->
<!--   select(수상) %>%  -->
<!--   unnest() %>%  -->
<!--   detailed_entries(when=수상년도, 수상등수, 수상프로그램, 수상지역) -->
<!-- ``` -->

# Presentation

```{r vitae-presentation}
resume_df %>% 
  select(발표) %>% 
  unnest() %>% 
  detailed_entries(발표제목, 발표일)
```

# Writing

```{r vitae-writing}
resume_df %>% 
  select(저서) %>% 
  unnest() %>% 
  detailed_entries(저서명, what=저자명, when=저작연도)
```


# Education

```{r vitae-education}
resume_df %>% 
  select(학교) %>% 
  unnest() %>% 
  detailed_entries(학교명, 학교위치)
```

# Extracurricular Activity

```{r extra-curricular}
resume_df %>% 
  select(특활) %>% 
  unnest() %>% 
  detailed_entries(with=특활명, where=특활지역, what=특활역할, when=특활기간)
```

